"use client";

import { useState, useMemo, useCallback } from "react";
import { toast } from "sonner";
import { Copy, Check, Trash2, Plus, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ToolEvents } from "@/lib/analytics";
import { cn } from "@/lib/utils";

interface RedirectRule {
  id: string;
  from: string;
  to: string;
  type: "301" | "302";
}

interface ErrorPages {
  "400": string;
  "401": string;
  "403": string;
  "404": string;
  "500": string;
  "503": string;
}

interface Config {
  forceHttps: boolean;
  wwwRedirect: "none" | "force-www" | "remove-www";
  disableDirListing: boolean;
  enableCustomErrors: boolean;
  customErrors: ErrorPages;
  enableGzip: boolean;
  browserCaching: boolean;
  xFrameOptions: boolean;
  xContentTypeOptions: boolean;
  blockBadBots: boolean;
  hotlinkProtection: boolean;
  hotlinkAllowedDomain: string;
  customRedirects: RedirectRule[];
}

const defaultConfig: Config = {
  forceHttps: true,
  wwwRedirect: "none",
  disableDirListing: true,
  enableCustomErrors: false,
  customErrors: {
    "400": "/errors/400.html",
    "401": "/errors/401.html",
    "403": "/errors/403.html",
    "404": "/errors/404.html",
    "500": "/errors/500.html",
    "503": "/errors/503.html",
  },
  enableGzip: true,
  browserCaching: true,
  xFrameOptions: true,
  xContentTypeOptions: true,
  blockBadBots: false,
  hotlinkProtection: false,
  hotlinkAllowedDomain: "example.com",
  customRedirects: [],
};

function generateHtaccess(config: Config): string {
  const lines: string[] = [];
  let rewriteEngineAdded = false;

  const ensureRewriteEngine = () => {
    if (!rewriteEngineAdded) {
      lines.push("RewriteEngine On");
      rewriteEngineAdded = true;
    }
  };

  lines.push("# Generated by htaccess-generator.tools.jagodana.com");
  lines.push("# .htaccess Configuration File");
  lines.push("");

  // Directory listing
  if (config.disableDirListing) {
    lines.push("# Disable directory listing");
    lines.push("Options -Indexes");
    lines.push("");
  }

  // Force HTTPS
  if (config.forceHttps) {
    lines.push("# Force HTTPS");
    ensureRewriteEngine();
    lines.push("RewriteCond %{HTTPS} off");
    lines.push("RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
    lines.push("");
  }

  // WWW redirect
  if (config.wwwRedirect === "force-www") {
    lines.push("# Force www");
    ensureRewriteEngine();
    lines.push("RewriteCond %{HTTP_HOST} !^www\\. [NC]");
    lines.push("RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
    lines.push("");
  } else if (config.wwwRedirect === "remove-www") {
    lines.push("# Remove www");
    ensureRewriteEngine();
    lines.push("RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]");
    lines.push("RewriteRule ^(.*)$ https://%1%{REQUEST_URI} [L,R=301]");
    lines.push("");
  }

  // Custom redirects
  const validRedirects = config.customRedirects.filter(r => r.from.trim() && r.to.trim());
  if (validRedirects.length > 0) {
    lines.push("# Custom Redirects");
    validRedirects.forEach(rule => {
      lines.push(`Redirect ${rule.type} ${rule.from.trim()} ${rule.to.trim()}`);
    });
    lines.push("");
  }

  // Custom error pages
  if (config.enableCustomErrors) {
    lines.push("# Custom Error Pages");
    const codes = ["400", "401", "403", "404", "500", "503"] as const;
    codes.forEach(code => {
      const path = config.customErrors[code].trim();
      if (path) lines.push(`ErrorDocument ${code} ${path}`);
    });
    lines.push("");
  }

  // Gzip compression
  if (config.enableGzip) {
    lines.push("# Gzip Compression");
    lines.push("<IfModule mod_deflate.c>");
    lines.push("  AddOutputFilterByType DEFLATE text/plain text/html text/xml text/css");
    lines.push(
      "  AddOutputFilterByType DEFLATE text/javascript application/javascript application/x-javascript"
    );
    lines.push(
      "  AddOutputFilterByType DEFLATE application/json application/xml application/xhtml+xml"
    );
    lines.push("  AddOutputFilterByType DEFLATE image/svg+xml application/rss+xml");
    lines.push("</IfModule>");
    lines.push("");
  }

  // Browser caching
  if (config.browserCaching) {
    lines.push("# Browser Caching");
    lines.push("<IfModule mod_expires.c>");
    lines.push("  ExpiresActive On");
    lines.push('  ExpiresByType image/jpeg "access plus 1 year"');
    lines.push('  ExpiresByType image/png "access plus 1 year"');
    lines.push('  ExpiresByType image/webp "access plus 1 year"');
    lines.push('  ExpiresByType image/gif "access plus 1 year"');
    lines.push('  ExpiresByType image/svg+xml "access plus 1 year"');
    lines.push('  ExpiresByType image/x-icon "access plus 1 year"');
    lines.push('  ExpiresByType text/css "access plus 1 month"');
    lines.push('  ExpiresByType text/javascript "access plus 1 month"');
    lines.push('  ExpiresByType application/javascript "access plus 1 month"');
    lines.push('  ExpiresByType application/pdf "access plus 1 month"');
    lines.push('  ExpiresByType text/html "access plus 0 seconds"');
    lines.push("</IfModule>");
    lines.push("");
  }

  // Security headers
  if (config.xFrameOptions || config.xContentTypeOptions) {
    lines.push("# Security Headers");
    lines.push("<IfModule mod_headers.c>");
    if (config.xFrameOptions) {
      lines.push('  Header always set X-Frame-Options "SAMEORIGIN"');
    }
    if (config.xContentTypeOptions) {
      lines.push('  Header always set X-Content-Type-Options "nosniff"');
    }
    lines.push('  Header always set Referrer-Policy "strict-origin-when-cross-origin"');
    lines.push("</IfModule>");
    lines.push("");
  }

  // Block bad bots
  if (config.blockBadBots) {
    lines.push("# Block Bad Bots");
    lines.push(
      'SetEnvIfNoCase User-Agent "^(ahrefsbot|mj12bot|semrushbot|dotbot|blexbot|exabot|ia_archiver)" bad_bot'
    );
    lines.push("Order Allow,Deny");
    lines.push("Allow from all");
    lines.push("Deny from env=bad_bot");
    lines.push("");
  }

  // Hotlink protection
  if (config.hotlinkProtection && config.hotlinkAllowedDomain.trim()) {
    const domain = config.hotlinkAllowedDomain.trim().replace(/^https?:\/\//, "");
    lines.push("# Hotlink Protection");
    ensureRewriteEngine();
    lines.push(
      `RewriteCond %{HTTP_REFERER} !^https://(www\\.)?${domain} [NC]`
    );
    lines.push("RewriteCond %{HTTP_REFERER} !^$");
    lines.push("RewriteRule \\.(jpg|jpeg|png|gif|webp|svg)$ - [F,NC]");
    lines.push("");
  }

  return lines.join("\n").trimEnd();
}

interface ToggleSwitchProps {
  checked: boolean;
  onChange: (v: boolean) => void;
  label: string;
  description?: string;
}

function ToggleSwitch({ checked, onChange, label, description }: ToggleSwitchProps) {
  return (
    <div className="flex items-center justify-between gap-4 py-2.5">
      <div className="min-w-0">
        <div className="text-sm font-medium leading-none">{label}</div>
        {description && (
          <div className="text-xs text-muted-foreground mt-1 leading-relaxed">
            {description}
          </div>
        )}
      </div>
      <button
        type="button"
        role="switch"
        aria-checked={checked}
        onClick={() => onChange(!checked)}
        className={cn(
          "relative inline-flex h-5 w-9 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand focus-visible:ring-offset-2",
          checked ? "bg-brand" : "bg-input"
        )}
      >
        <span
          className={cn(
            "pointer-events-none inline-block h-4 w-4 rounded-full bg-white shadow-sm transition-transform",
            checked ? "translate-x-4" : "translate-x-0"
          )}
        />
      </button>
    </div>
  );
}

function SectionDivider() {
  return <div className="border-t border-border/50 my-1" />;
}

export function HtaccessGeneratorTool() {
  const [config, setConfig] = useState<Config>(defaultConfig);
  const [copied, setCopied] = useState(false);

  const output = useMemo(() => generateHtaccess(config), [config]);

  const update = useCallback(
    <K extends keyof Config>(key: K, value: Config[K]) => {
      setConfig(prev => ({ ...prev, [key]: value }));
      ToolEvents.toolUsed("config-change");
    },
    []
  );

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      toast.success("Copied to clipboard!");
      ToolEvents.resultCopied();
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Copy failed — please select and copy manually.");
    }
  }, [output]);

  const handleReset = useCallback(() => {
    setConfig(defaultConfig);
    toast.success("Reset to defaults");
  }, []);

  const addRedirect = useCallback(() => {
    setConfig(prev => ({
      ...prev,
      customRedirects: [
        ...prev.customRedirects,
        {
          id: Math.random().toString(36).slice(2),
          from: "/old-page",
          to: "/new-page",
          type: "301" as const,
        },
      ],
    }));
  }, []);

  const removeRedirect = useCallback((id: string) => {
    setConfig(prev => ({
      ...prev,
      customRedirects: prev.customRedirects.filter(r => r.id !== id),
    }));
  }, []);

  const updateRedirect = useCallback(
    (id: string, field: keyof Omit<RedirectRule, "id">, value: string) => {
      setConfig(prev => ({
        ...prev,
        customRedirects: prev.customRedirects.map(r =>
          r.id === id ? { ...r, [field]: value } : r
        ),
      }));
    },
    []
  );

  return (
    <div className="max-w-7xl mx-auto">
      <div className="grid lg:grid-cols-2 gap-6 items-start">
        {/* Left — Configuration panels */}
        <div className="space-y-4">
          <Tabs defaultValue="basic">
            <TabsList className="grid grid-cols-4 w-full">
              <TabsTrigger value="basic">Basic</TabsTrigger>
              <TabsTrigger value="perf">Perf</TabsTrigger>
              <TabsTrigger value="security">Security</TabsTrigger>
              <TabsTrigger value="redirects">Redirects</TabsTrigger>
            </TabsList>

            {/* Basic Tab */}
            <TabsContent value="basic" className="mt-4 space-y-4">
              <Card className="p-4">
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">
                  HTTPS &amp; Domain
                </p>
                <ToggleSwitch
                  checked={config.forceHttps}
                  onChange={v => update("forceHttps", v)}
                  label="Force HTTPS"
                  description="Redirect all HTTP traffic to HTTPS (301)"
                />
                <SectionDivider />
                <div className="py-2.5">
                  <div className="text-sm font-medium mb-2">WWW Redirect</div>
                  <div className="flex gap-2">
                    {(["none", "force-www", "remove-www"] as const).map(opt => (
                      <button
                        key={opt}
                        onClick={() => update("wwwRedirect", opt)}
                        className={cn(
                          "flex-1 py-1.5 px-2 rounded-md text-xs font-medium border transition-colors",
                          config.wwwRedirect === opt
                            ? "bg-brand text-white border-brand"
                            : "border-border hover:border-brand/50 text-foreground"
                        )}
                      >
                        {opt === "none" ? "None" : opt === "force-www" ? "Add www" : "Remove www"}
                      </button>
                    ))}
                  </div>
                </div>
                <SectionDivider />
                <ToggleSwitch
                  checked={config.disableDirListing}
                  onChange={v => update("disableDirListing", v)}
                  label="Disable Directory Listing"
                  description="Hide folder contents — prevents visitors from browsing files"
                />
              </Card>

              <Card className="p-4">
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">
                  Error Pages
                </p>
                <ToggleSwitch
                  checked={config.enableCustomErrors}
                  onChange={v => update("enableCustomErrors", v)}
                  label="Custom Error Pages"
                  description="Set custom HTML paths for 4xx and 5xx errors"
                />
                {config.enableCustomErrors && (
                  <div className="mt-3 space-y-2">
                    {(["400", "401", "403", "404", "500", "503"] as const).map(code => (
                      <div key={code} className="flex items-center gap-2">
                        <span className="text-xs font-mono bg-muted px-2 py-1 rounded w-10 text-center shrink-0">
                          {code}
                        </span>
                        <Input
                          value={config.customErrors[code]}
                          onChange={e =>
                            update("customErrors", {
                              ...config.customErrors,
                              [code]: e.target.value,
                            })
                          }
                          className="h-7 text-xs font-mono"
                          placeholder={`/errors/${code}.html`}
                        />
                      </div>
                    ))}
                  </div>
                )}
              </Card>
            </TabsContent>

            {/* Performance Tab */}
            <TabsContent value="perf" className="mt-4 space-y-4">
              <Card className="p-4">
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">
                  Compression
                </p>
                <ToggleSwitch
                  checked={config.enableGzip}
                  onChange={v => update("enableGzip", v)}
                  label="Gzip Compression"
                  description="Compress HTML, CSS, JS, JSON, and SVG responses via mod_deflate"
                />
              </Card>
              <Card className="p-4">
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">
                  Browser Caching
                </p>
                <ToggleSwitch
                  checked={config.browserCaching}
                  onChange={v => update("browserCaching", v)}
                  label="Browser Caching"
                  description="Sets Expires headers: images 1 year, CSS/JS 1 month, HTML no-cache"
                />
              </Card>
            </TabsContent>

            {/* Security Tab */}
            <TabsContent value="security" className="mt-4 space-y-4">
              <Card className="p-4">
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">
                  Security Headers
                </p>
                <ToggleSwitch
                  checked={config.xFrameOptions}
                  onChange={v => update("xFrameOptions", v)}
                  label="X-Frame-Options"
                  description="Blocks clickjacking — prevents your site from being embedded in iframes"
                />
                <SectionDivider />
                <ToggleSwitch
                  checked={config.xContentTypeOptions}
                  onChange={v => update("xContentTypeOptions", v)}
                  label="X-Content-Type-Options"
                  description="Prevents MIME-type sniffing attacks"
                />
              </Card>

              <Card className="p-4">
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">
                  Bot &amp; Scraper Protection
                </p>
                <ToggleSwitch
                  checked={config.blockBadBots}
                  onChange={v => update("blockBadBots", v)}
                  label="Block Bad Bots"
                  description="Deny AhrefsBot, MJ12Bot, SemRushBot, DotBot, and other scrapers"
                />
              </Card>

              <Card className="p-4">
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">
                  Hotlink Protection
                </p>
                <ToggleSwitch
                  checked={config.hotlinkProtection}
                  onChange={v => update("hotlinkProtection", v)}
                  label="Hotlink Protection"
                  description="Block external sites from embedding your images and stealing bandwidth"
                />
                {config.hotlinkProtection && (
                  <div className="mt-3">
                    <label className="text-xs text-muted-foreground block mb-1.5">
                      Your domain (allowed to hotlink)
                    </label>
                    <Input
                      value={config.hotlinkAllowedDomain}
                      onChange={e => update("hotlinkAllowedDomain", e.target.value)}
                      placeholder="yourdomain.com"
                      className="h-8 text-sm font-mono"
                    />
                  </div>
                )}
              </Card>
            </TabsContent>

            {/* Redirects Tab */}
            <TabsContent value="redirects" className="mt-4 space-y-4">
              <Card className="p-4">
                <div className="flex items-center justify-between mb-3">
                  <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                    Custom Redirect Rules
                  </p>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={addRedirect}
                    className="h-7 text-xs gap-1"
                  >
                    <Plus className="h-3 w-3" />
                    Add Rule
                  </Button>
                </div>

                {config.customRedirects.length === 0 && (
                  <p className="text-sm text-muted-foreground text-center py-6">
                    No redirect rules yet. Click &quot;Add Rule&quot; to create one.
                  </p>
                )}

                <div className="space-y-3">
                  {config.customRedirects.map((rule, idx) => (
                    <div
                      key={rule.id}
                      className="p-3 rounded-lg bg-muted/30 border border-border/50"
                    >
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-xs text-muted-foreground font-medium">
                          Rule {idx + 1}
                        </span>
                        <button
                          type="button"
                          onClick={() => removeRedirect(rule.id)}
                          className="text-muted-foreground hover:text-destructive transition-colors"
                          aria-label="Remove redirect rule"
                        >
                          <Trash2 className="h-3.5 w-3.5" />
                        </button>
                      </div>
                      <div className="grid grid-cols-2 gap-2 mb-2">
                        <div>
                          <label className="text-xs text-muted-foreground block mb-1">
                            From (path)
                          </label>
                          <Input
                            value={rule.from}
                            onChange={e => updateRedirect(rule.id, "from", e.target.value)}
                            placeholder="/old-page"
                            className="h-7 text-xs font-mono"
                          />
                        </div>
                        <div>
                          <label className="text-xs text-muted-foreground block mb-1">
                            To (URL or path)
                          </label>
                          <Input
                            value={rule.to}
                            onChange={e => updateRedirect(rule.id, "to", e.target.value)}
                            placeholder="/new-page"
                            className="h-7 text-xs font-mono"
                          />
                        </div>
                      </div>
                      <div className="flex gap-2">
                        {(["301", "302"] as const).map(type => (
                          <button
                            key={type}
                            type="button"
                            onClick={() => updateRedirect(rule.id, "type", type)}
                            className={cn(
                              "py-1 px-3 rounded text-xs font-mono border transition-colors",
                              rule.type === type
                                ? "bg-brand text-white border-brand"
                                : "border-border hover:border-brand/50 text-foreground"
                            )}
                          >
                            {type} {type === "301" ? "(Permanent)" : "(Temporary)"}
                          </button>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </Card>
            </TabsContent>
          </Tabs>
        </div>

        {/* Right — Live output */}
        <div className="flex flex-col gap-3">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-semibold">.htaccess Output</h3>
            <div className="flex gap-2">
              <Button
                size="sm"
                variant="outline"
                onClick={handleReset}
                className="h-8 text-xs gap-1.5"
              >
                <RotateCcw className="h-3 w-3" />
                Reset
              </Button>
              <Button
                size="sm"
                onClick={handleCopy}
                className="h-8 text-xs gap-1.5 bg-gradient-to-r from-brand to-brand-accent text-white hover:opacity-90"
              >
                {copied ? (
                  <>
                    <Check className="h-3 w-3" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="h-3 w-3" />
                    Copy
                  </>
                )}
              </Button>
            </div>
          </div>

          <div className="rounded-xl border border-border/50 bg-zinc-950 dark:bg-zinc-900 overflow-hidden">
            <div className="flex items-center gap-1.5 px-4 py-2.5 border-b border-white/10 bg-white/5">
              <div className="h-2.5 w-2.5 rounded-full bg-red-500/80" />
              <div className="h-2.5 w-2.5 rounded-full bg-amber-500/80" />
              <div className="h-2.5 w-2.5 rounded-full bg-green-500/80" />
              <span className="ml-2 text-xs text-white/40 font-mono">.htaccess</span>
            </div>
            <pre className="p-4 text-xs font-mono text-green-400 overflow-auto max-h-[580px] leading-relaxed whitespace-pre-wrap break-words">
              {output}
            </pre>
          </div>

          <p className="text-xs text-muted-foreground text-center">
            All rules are generated in your browser. Nothing is sent to a server.
          </p>
        </div>
      </div>
    </div>
  );
}
